# Generated by Django 5.2.1 on 2025-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
