# Generated by Django 5.2.1 on 2025-07-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_remove_spotifyuser_id_alter_spotifyuser_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='bio',
            field=models.TextField(blank=True, default='Apaixonado por música, sempre descobrindo novos sons e compartilhando as melhores playlists.', max_length=500),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='custom_rewind_title',
            field=models.CharField(blank=True, default='Meu Rewind Musical', max_length=100),
        ),
        migrations.CreateModel(
            name='CustomRewindItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_rewind_items', to='spotify_app.spotifyuser')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
