# Generated by Django 5.2.1 on 2025-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_spotifyuser_bio_spotifyuser_custom_rewind_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customrewinditem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customrewinditem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customrewinditem',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='customrewinditem',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='customrewinditem',
            name='created_at',
        ),
    ]
