# Generated by Django 5.2.1 on 2025-07-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_alter_customrewinditem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrewinditem',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customrewinditem',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customrewinditem',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customrewinditem',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
